/** Declaration file generated by dts-gen */

declare module "sdp-jingle-json" {

  export function toCandidateJSON(line: any): any;

  export function toCandidateSDP(candidate: any): any;

  export function toIncomingJSONAnswer(sdp: any, creators: any): any;

  export function toIncomingJSONOffer(sdp: any, creators: any): any;

  export function toIncomingMediaJSONAnswer(sdp: any, creator: any): any;

  export function toIncomingMediaJSONOffer(sdp: any, creator: any): any;

  export function toIncomingMediaSDPAnswer(media: any): any;

  export function toIncomingMediaSDPOffer(media: any): any;

  export function toIncomingSDPAnswer(session: any): any;

  export function toIncomingSDPOffer(session: any): any;

  export function toMediaJSON(media: any, session: any, opts: any): any;

  export function toMediaSDP(content: any, opts: any): any;

  export function toOutgoingJSONAnswer(sdp: any, creators: any): any;

  export function toOutgoingJSONOffer(sdp: any, creators: any): any;

  export function toOutgoingMediaJSONAnswer(sdp: any, creator: any): any;

  export function toOutgoingMediaJSONOffer(sdp: any, creator: any): any;

  export function toOutgoingMediaSDPAnswer(media: any): any;

  export function toOutgoingMediaSDPOffer(media: any): any;

  export function toOutgoingSDPAnswer(session: any): any;

  export function toOutgoingSDPOffer(session: any): any;

  export function toSessionJSON(sdp: any, opts: any): any;

  export function toSessionSDP(session: any, opts: any): any;

}